TILE_GRASS = 0
TILE_FOREST = 1
TILE_MOUNTAIN = 2
TILE_HOUSE = 3
EMPTY = 4
TILE_WATER = 5
TILE_COAST_X = 6
TILE_COAST_XFLIP = 7
TILE_COASTY = 8
TILE_COASTY_YFLIP = 9
TILE_BRIDGE = 10
TILE_CLIFFBTLBR = 11
TILE_CLIFF_B_TLBR_XFLIP = 12
TILE_CLIFF_B_TLBR_YFLIP = 13
TILE_CLIFF_B_TLBR_XYFLIP = 14
TILE_CLIFF_TTLBR = 15
TILE_CLIFF_TTLBR_XFLIP = 16
TILE_CLIFF_STRAIGHT = 17
TILE_STAIRS = 18
TILE_SHOP = 19
WALL_TOP = 20
WALL_SIDE = 21
TILE_CLIFF_TOP = 22
TILE_CLIFF_TOP_YFLIP = 23
TILE_CLIFF_RIGHT = 24
TILE_CLIFF_RIGHT_XFLIP = 25
TILE_COAST_CORNER_BR = 26
TILE_COAST_CORNER_BR_XFLIP = 27
TILE_COAST_CORNER_BR_YFLIP = 28
TILE_COAST_CORNER_BR_XYFLIP = 29
TILE_WATER_CLIFF = 30
TILE_WATER_CLIFF_YFLIP = 31
TILE_WATER_CLIFF_XFLIP = 32
TILE_WATER_CLIFF_XYFLIP = 33
TILE_SEIZE = 34
TILE_BARRIER = 35
TILE_CLIFF_WATER = 36
TILE_CLIFF_WATER_YFLIP = 37
TILE_CLIFF_WATER_XFLIP = 38
TILE_CLIFF_WATER_XYFLIP = 39
TILE_BLOCKADE = 40
TILE_HOUSE_DESTROYED = 41

tiles = {
	TILE_GRASS: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([0, 64, 0, 64, 4, 0, 4, 0])), "XFLIP": False, "YFLIP": False},
	TILE_FOREST: {"sprite": (bytearray([255, 255, 255, 255, 127, 255, 255, 255]), bytearray([0, 0, 96, 124, 255, 124, 96, 0])), "XFLIP": False, "YFLIP": False},
	TILE_MOUNTAIN: {"sprite": (bytearray([255, 255, 255, 255, 255, 252, 227, 31]), bytearray([192, 240, 252, 255, 255, 255, 252, 224])), "XFLIP": False, "YFLIP": False},
	TILE_HOUSE: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([8, 252, 142, 239, 239, 142, 252, 8])), "XFLIP": False, "YFLIP": False},
	TILE_WATER: {"sprite": (bytearray([0, 4, 2, 4, 64, 32, 64, 0, 0, 0, 4, 66, 36, 64, 0, 0]), bytearray([0, 4, 2, 4, 64, 32, 64, 0, 0, 0, 4, 66, 36, 64, 0, 0])), "XFLIP": False, "YFLIP": False},
	TILE_COAST_X: {"sprite": (bytearray([0, 64, 160, 0, 7, 136, 86, 239, 0, 4, 10, 0, 64, 161, 86, 239]), bytearray([0, 64, 160, 0, 7, 136, 16, 0, 0, 4, 10, 0, 64, 161, 16, 0])), "XFLIP": False, "YFLIP": False},
	TILE_COASTY: {"sprite": (bytearray([160, 208, 136, 16, 164, 194, 196, 160, 160, 196, 130, 68, 160, 208, 208, 160]), bytearray([32, 16, 8, 16, 36, 2, 4, 32, 32, 4, 2, 68, 32, 16, 16, 32])), "XFLIP": False, "YFLIP": False},
	TILE_BRIDGE: {"sprite": (bytearray([126, 126, 126, 126, 126, 126, 126, 126]), bytearray([193, 193, 193, 193, 193, 193, 193, 193])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFF_TOP: {"sprite": (bytearray([254, 254, 254, 254, 254, 254, 254, 254]), bytearray([1, 1, 1, 1, 1, 1, 1, 1])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFF_RIGHT: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 0]), bytearray([0, 0, 0, 0, 0, 0, 0, 255])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFFBTLBR: {"sprite": (bytearray([1, 3, 7, 15, 31, 63, 127, 255]), bytearray([255, 254, 252, 248, 240, 224, 192, 128])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFF_TTLBR: {"sprite": (bytearray([127, 191, 223, 239, 247, 251, 253, 254]), bytearray([128, 64, 32, 16, 72, 36, 66, 1])), "XFLIP": False, "YFLIP": False},
	TILE_CLIFF_STRAIGHT: {"sprite": (bytearray([129, 129, 129, 129, 129, 129, 129, 129]), bytearray([255, 255, 255, 255, 255, 255, 255, 255])), "XFLIP": False, "YFLIP": False},
	TILE_COAST_CORNER_BR: {"sprite": (bytearray([160, 208, 160, 0, 164, 217, 194, 247, 136, 200, 128, 4, 130, 192, 194, 247]), bytearray([32, 16, 32, 0, 36, 25, 0, 0, 8, 8, 0, 4, 2, 0, 0, 0])),"XFLIP": False, "YFLIP": False },
	TILE_STAIRS: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([85, 85, 85, 85, 85, 85, 85, 85])), "XFLIP": False, "YFLIP": False},
	TILE_SHOP: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([254, 2, 5, 229, 229, 5, 2, 254])), "XFLIP": False, "YFLIP": False},
	WALL_TOP: {"sprite": (bytearray([127, 127, 127, 127, 127, 127, 127, 1]), bytearray([128, 254, 254, 254, 254, 254, 254, 254])), "XFLIP": False, "YFLIP": False},
	WALL_SIDE: {"sprite": (bytearray([17, 17, 68, 68, 17, 17, 68, 68]), bytearray([85, 17, 85, 68, 85, 17, 85, 68])), "XFLIP": False, "YFLIP": False},
	TILE_WATER_CLIFF: {"sprite": (bytearray([0, 1, 3, 7, 15, 31, 63, 127]), bytearray([1, 2, 4, 8, 16, 32, 64, 128])), "XFLIP": False, "YFLIP": False},
    TILE_SEIZE: {"sprite": (bytearray([255, 127, 127, 127, 127, 127, 127, 255]), bytearray([252, 134, 131, 129, 129, 131, 134, 252])), "XFLIP": False, "YFLIP": False},
    TILE_CLIFF_WATER: {"sprite": (bytearray([128, 64, 32, 16, 136, 68, 2, 145, 128, 64, 32, 208, 72, 36, 130, 77]), bytearray([255, 127, 63, 31, 143, 71, 3, 145, 255, 127, 63, 223, 79, 39, 131, 77])), "XFLIP": False, "YFLIP": False},
    TILE_BLOCKADE: {"sprite": (bytearray([0, 122, 4, 106, 86, 32, 94, 0]), bytearray([255, 255, 255, 255, 255, 255, 255, 255])), "XFLIP": False, "YFLIP": False},
    TILE_HOUSE_DESTROYED: {"sprite": (bytearray([255, 255, 255, 255, 255, 255, 255, 255]), bytearray([192, 240, 152, 248, 252, 176, 224, 0])), "XFLIP": False, "YFLIP": False},
}

_tile_flip_overrides = {
    TILE_COAST_XFLIP: (TILE_COAST_X, True, False),
    TILE_COASTY_YFLIP: (TILE_COASTY, False, True),
    TILE_CLIFF_B_TLBR_XFLIP: (TILE_CLIFFBTLBR, True, False),
    TILE_CLIFF_B_TLBR_YFLIP: (TILE_CLIFFBTLBR, False, True),
    TILE_CLIFF_B_TLBR_XYFLIP: (TILE_CLIFFBTLBR, True, True),
    TILE_CLIFF_TTLBR_XFLIP: (TILE_CLIFF_TTLBR, True, False),
    TILE_CLIFF_RIGHT_XFLIP: (TILE_CLIFF_RIGHT, True, False),
    TILE_COAST_CORNER_BR_XFLIP: (TILE_COAST_CORNER_BR, True, False),
    TILE_COAST_CORNER_BR_YFLIP: (TILE_COAST_CORNER_BR, False, True),
    TILE_COAST_CORNER_BR_XYFLIP: (TILE_COAST_CORNER_BR, True, True),
    TILE_WATER_CLIFF_YFLIP: (TILE_WATER_CLIFF, False, True),
    TILE_WATER_CLIFF_XFLIP: (TILE_WATER_CLIFF, True, False),
    TILE_WATER_CLIFF_XYFLIP: (TILE_WATER_CLIFF, True, True),
    TILE_CLIFF_WATER_YFLIP: (TILE_CLIFF_WATER, False, True),
    TILE_CLIFF_WATER_XFLIP: (TILE_CLIFF_WATER, True, False),
    TILE_CLIFF_WATER_XYFLIP: (TILE_CLIFF_WATER, True, True),
}

def get_tile_data(tile_type: int):
    tileData = tiles.get(tile_type, None)
    size_x = 8
    size_y = 8
    if tileData:
        return tileData["sprite"], tileData["XFLIP"], tileData["YFLIP"], size_x, size_y

    override = _tile_flip_overrides.get(tile_type, None)
    if override:
        base_type, x_flip, y_flip = override
        baseData = tiles.get(base_type, None)
        if baseData:
            return baseData["sprite"], x_flip, y_flip, size_x, size_y

    return None, False, False, size_x, size_y

canWalkOn = {
	TILE_GRASS: True,
	TILE_FOREST: True,
	TILE_MOUNTAIN: False,
	TILE_HOUSE: True,
    TILE_HOUSE_DESTROYED: True,
	EMPTY: True,
	TILE_WATER: False,
	TILE_COAST_X: False,
	TILE_COAST_XFLIP: False,
	TILE_COASTY: False,
	TILE_COASTY_YFLIP: False,
	TILE_BRIDGE: True,
	TILE_CLIFFBTLBR: False,
	TILE_CLIFF_B_TLBR_XFLIP: False,
	TILE_CLIFF_B_TLBR_YFLIP: False,
	TILE_CLIFF_B_TLBR_XYFLIP: False,
	TILE_CLIFF_TTLBR: False,
	TILE_CLIFF_TTLBR_XFLIP: False,
	TILE_CLIFF_STRAIGHT: False,
	TILE_STAIRS: True,
	TILE_SHOP: True,
	WALL_TOP: False,
	WALL_SIDE: False,
	TILE_CLIFF_TOP: True,
	TILE_CLIFF_TOP_YFLIP: True,
	TILE_CLIFF_RIGHT: True,
	TILE_CLIFF_RIGHT_XFLIP: True,
	TILE_COAST_CORNER_BR: False,
	TILE_COAST_CORNER_BR_XFLIP: False,
	TILE_COAST_CORNER_BR_YFLIP: False,
	TILE_COAST_CORNER_BR_XYFLIP: False,
    TILE_SEIZE: True,
    TILE_BARRIER: False,
}

tileEncumberence = {
	TILE_FOREST: 2,
}

tileEvation = {
	TILE_FOREST: 20,
	TILE_GRASS: 5,
	TILE_HOUSE: 10,
	TILE_SHOP: 10,
}

class MapData:
    def get_map1():
        return [
        [TILE_COASTY, TILE_COASTY, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
        [TILE_GRASS, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_WATER, TILE_WATER, TILE_WATER],
        [TILE_GRASS, TILE_SEIZE, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_COASTY, TILE_COASTY],
        [TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_FOREST],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN],
        [TILE_MOUNTAIN, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, TILE_GRASS, TILE_FOREST, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN],
        [WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP],
        [WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, EMPTY, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE],
        [TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN, TILE_MOUNTAIN],
        [TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN],
        [TILE_MOUNTAIN, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_MOUNTAIN],
        [TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_HOUSE, TILE_SHOP, TILE_HOUSE, TILE_MOUNTAIN],
        [TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN],
        [TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST],
        [TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST],
        [TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST]
    ]

    def get_map2():
        return [
        [TILE_FOREST, TILE_GRASS, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, TILE_GRASS, TILE_FOREST],
        [TILE_GRASS, EMPTY, TILE_HOUSE, TILE_GRASS, TILE_HOUSE, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, TILE_GRASS],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS],
        [EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_RIGHT_XFLIP, TILE_GRASS, EMPTY, EMPTY],
        [TILE_GRASS, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_CLIFFBTLBR, EMPTY, EMPTY, TILE_FOREST],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_MOUNTAIN, TILE_FOREST, TILE_CLIFF_B_TLBR_XYFLIP, TILE_STAIRS, TILE_STAIRS, WALL_TOP],
        [EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, WALL_SIDE],
        [TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY],
        [WALL_TOP, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS],
        [WALL_SIDE, EMPTY, TILE_FOREST, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY],
        [TILE_GRASS, EMPTY, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_FOREST, TILE_MOUNTAIN, TILE_FOREST, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY],
        [EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS],
        [TILE_GRASS, TILE_SEIZE, EMPTY, EMPTY, TILE_FOREST, EMPTY, TILE_MOUNTAIN, EMPTY, TILE_GRASS, EMPTY, TILE_FOREST, EMPTY, EMPTY, WALL_TOP],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_HOUSE, WALL_SIDE],
        [TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_FOREST, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY]
    ]

    def get_map3():
        return [
        [EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, TILE_GRASS, TILE_FOREST, TILE_GRASS],
        [EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, EMPTY, TILE_GRASS, TILE_COAST_XFLIP, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR, EMPTY, TILE_SEIZE, EMPTY],
        [TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_COAST_X, TILE_GRASS, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XFLIP, TILE_COAST_CORNER_BR, EMPTY, EMPTY, EMPTY, TILE_GRASS],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY],
        [WALL_TOP, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_TOP, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT],
        [WALL_SIDE, EMPTY, EMPTY, EMPTY, WALL_SIDE, TILE_FOREST, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_FOREST, TILE_HOUSE, TILE_GRASS],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, WALL_TOP, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_TOP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT],
        [TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_GRASS, TILE_GRASS, WALL_SIDE, EMPTY, EMPTY, EMPTY, EMPTY, WALL_SIDE, TILE_FOREST, TILE_GRASS],
        [TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY]
    ]

    def get_map4():
        return [
        [TILE_HOUSE, TILE_HOUSE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS],
        [EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, TILE_GRASS, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY],
        [EMPTY, TILE_FOREST, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XYFLIP],
        [EMPTY, TILE_FOREST, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_XFLIP],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XYFLIP, TILE_WATER],
        [EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_COAST_XFLIP, TILE_WATER],
        [EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, TILE_MOUNTAIN, TILE_COAST_XFLIP, TILE_WATER],
        [EMPTY, TILE_GRASS, EMPTY, TILE_SHOP, TILE_MOUNTAIN, EMPTY, EMPTY, TILE_COAST_XFLIP, TILE_WATER],
        [EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_GRASS, EMPTY, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER],
        [EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, TILE_COAST_CORNER_BR_XFLIP],
        [EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_GRASS, TILE_GRASS, TILE_SEIZE, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_HOUSE, EMPTY],
        [EMPTY, TILE_GRASS, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS]
    ]

    def get_map5():
        return [
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, TILE_SHOP, TILE_HOUSE, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, EMPTY],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, EMPTY],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, EMPTY, TILE_FOREST, EMPTY, EMPTY],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_WATER, TILE_COASTY, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS],
        [TILE_COAST_X, TILE_GRASS, TILE_BRIDGE, TILE_BRIDGE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY],
        [TILE_WATER, TILE_COASTY_YFLIP, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_HOUSE, TILE_GRASS],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_HOUSE],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_FOREST, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, EMPTY, TILE_GRASS, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_FOREST, TILE_CLIFF_RIGHT, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY],
        [TILE_SEIZE, EMPTY, TILE_BRIDGE, TILE_BRIDGE, TILE_BRIDGE, TILE_BRIDGE, EMPTY, TILE_FOREST, EMPTY, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_GRASS, EMPTY],
        [TILE_FOREST, TILE_CLIFF_RIGHT, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY]
    ]

    def get_map6():
        return [
        [WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP],
        [WALL_TOP, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_TOP, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_TOP, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_SIDE, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, TILE_SEIZE, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_TOP, EMPTY, WALL_TOP, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_SIDE, EMPTY, WALL_SIDE, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_SIDE, WALL_SIDE, EMPTY, WALL_SIDE, WALL_SIDE, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_TOP, EMPTY, WALL_TOP, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, WALL_SIDE, EMPTY, WALL_SIDE, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_SIDE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, TILE_FOREST, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP],
        [WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP]
    ]

    def get_map7():
        return [
        [TILE_FOREST, TILE_SHOP, TILE_GRASS, TILE_SHOP, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_MOUNTAIN],
        [TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_FOREST, EMPTY, TILE_GRASS, TILE_SEIZE, TILE_GRASS],
        [EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_GRASS, EMPTY],
        [TILE_FOREST, TILE_GRASS, TILE_FOREST, EMPTY, TILE_FOREST, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN],
        [TILE_GRASS, TILE_FOREST, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, TILE_GRASS],
        [EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_HOUSE, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, TILE_FOREST],
        [EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_FOREST, TILE_MOUNTAIN, TILE_FOREST, TILE_MOUNTAIN, EMPTY, TILE_FOREST, TILE_GRASS],
        [EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY],
        [TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_MOUNTAIN],
        [TILE_GRASS, TILE_HOUSE, EMPTY, TILE_FOREST, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_FOREST, TILE_FOREST, TILE_GRASS, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS],
        [EMPTY, TILE_GRASS, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY]
    ]

    def get_map8():
        return [
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
        [TILE_WATER_CLIFF_YFLIP, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_WATER_CLIFF_XYFLIP, TILE_WATER, TILE_COAST_X, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_WATER, TILE_WATER],
        [TILE_MOUNTAIN, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_SEIZE, EMPTY, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_GRASS, TILE_WATER, TILE_COAST_X, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_WATER],
        [TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_WATER, TILE_COAST_X, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_WATER],
        [TILE_CLIFFBTLBR, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XFLIP, TILE_WATER, TILE_COAST_X, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_COAST_XFLIP],
        [TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_COAST_XFLIP, TILE_COAST_CORNER_BR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_COAST_XFLIP],
        [TILE_MOUNTAIN, TILE_GRASS, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN, TILE_COAST_CORNER_BR_XYFLIP, TILE_COAST_X, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_COAST_XFLIP],
        [TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_COAST_CORNER_BR_XYFLIP, TILE_WATER, TILE_COAST_X, WALL_TOP, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_COAST_XFLIP],
        [TILE_COAST_X, TILE_GRASS, EMPTY, TILE_FOREST, TILE_FOREST, TILE_FOREST, EMPTY, TILE_GRASS, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_COAST_X, WALL_SIDE, WALL_TOP, WALL_TOP, EMPTY, EMPTY, WALL_TOP, WALL_TOP, WALL_TOP, TILE_COAST_XFLIP],
        [TILE_COAST_X, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_FOREST, TILE_FOREST, TILE_COAST_CORNER_BR_XFLIP, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, WALL_SIDE, WALL_SIDE, EMPTY, EMPTY, WALL_SIDE, WALL_SIDE, WALL_SIDE, TILE_COAST_XFLIP],
        [TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_COAST_XFLIP, TILE_COAST_X, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_HOUSE, TILE_HOUSE, TILE_MOUNTAIN, TILE_COAST_XFLIP],
        [TILE_WATER, TILE_COAST_X, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_BRIDGE, TILE_BRIDGE, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, TILE_COAST_XFLIP],
        [TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_MOUNTAIN, TILE_GRASS, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_COAST_XFLIP, TILE_COAST_X, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_COAST_CORNER_BR_XYFLIP, TILE_WATER],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, EMPTY, TILE_GRASS, TILE_GRASS, TILE_MOUNTAIN, TILE_COAST_XFLIP, TILE_WATER],
        [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_WATER, TILE_WATER]
    ]

    def get_map9():
        return [
        [TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, TILE_FOREST, TILE_MOUNTAIN, TILE_GRASS, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, TILE_FOREST, TILE_FOREST, WALL_TOP, WALL_TOP, TILE_CLIFF_TTLBR_XFLIP, TILE_SEIZE, TILE_CLIFF_TTLBR, WALL_TOP, WALL_TOP],
        [TILE_FOREST, TILE_HOUSE, TILE_HOUSE, TILE_SHOP, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, WALL_SIDE, WALL_SIDE, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_SIDE, WALL_SIDE],
        [TILE_MOUNTAIN, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS],
        [TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS],
        [TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_TOP, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [WALL_SIDE, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, WALL_SIDE, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XFLIP],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_FOREST, TILE_GRASS, TILE_GRASS, TILE_FOREST, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP],
        [TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_GRASS, TILE_MOUNTAIN],
        [TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_MOUNTAIN, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN],
        [TILE_HOUSE, TILE_FOREST, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_CLIFF_STRAIGHT],
        [TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_FOREST, TILE_FOREST, TILE_GRASS, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_GRASS, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [TILE_MOUNTAIN, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_MOUNTAIN, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_FOREST],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY],
        [TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, EMPTY, EMPTY]
    ]

    def get_map10():
        return [
    [TILE_GRASS, TILE_MOUNTAIN, TILE_MOUNTAIN, TILE_FOREST, TILE_COAST_XFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COASTY, TILE_COASTY, TILE_COASTY, TILE_COASTY],
    [TILE_COAST_CORNER_BR_YFLIP, TILE_FOREST, TILE_MOUNTAIN, TILE_GRASS, TILE_COAST_XFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_X, TILE_GRASS, TILE_FOREST, TILE_MOUNTAIN, TILE_GRASS],
    [TILE_COAST_X, TILE_GRASS, TILE_GRASS, TILE_COAST_CORNER_BR_XYFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COAST_CORNER_BR_YFLIP, TILE_GRASS, TILE_FOREST, TILE_COAST_CORNER_BR_XYFLIP],
    [TILE_WATER, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_COASTY_YFLIP, TILE_COASTY_YFLIP, TILE_WATER],
    [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER_CLIFF_YFLIP, TILE_CLIFF_TOP, TILE_CLIFF_TOP, TILE_BARRIER, TILE_BARRIER, TILE_CLIFF_TOP, TILE_BARRIER, TILE_BARRIER, TILE_CLIFF_TOP, TILE_CLIFF_TOP, TILE_WATER_CLIFF_XYFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
    [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER_CLIFF_YFLIP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_WATER_CLIFF_XYFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
    [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER_CLIFF_YFLIP, EMPTY, TILE_FOREST, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, EMPTY, TILE_WATER_CLIFF_XYFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
    [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER_CLIFF_YFLIP, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_WATER_CLIFF_XYFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
    [TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER, TILE_CLIFFBTLBR, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_WATER, TILE_WATER, TILE_WATER, TILE_WATER],
    [TILE_WATER, TILE_WATER_CLIFF_YFLIP, TILE_CLIFF_TOP, TILE_CLIFF_TOP, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFFBTLBR, TILE_GRASS, TILE_FOREST, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_B_TLBR_YFLIP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFFBTLBR, TILE_FOREST, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_B_TLBR_YFLIP, TILE_CLIFF_TOP, TILE_CLIFF_TOP, TILE_WATER_CLIFF_XYFLIP, TILE_WATER],
    [TILE_WATER, TILE_CLIFF_RIGHT_XFLIP, TILE_FOREST, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFFBTLBR, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_B_TLBR_YFLIP, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFFBTLBR, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_B_TLBR_YFLIP, EMPTY, EMPTY, TILE_FOREST, TILE_CLIFF_RIGHT, TILE_WATER],
    [TILE_WATER, TILE_CLIFF_RIGHT_XFLIP, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_B_TLBR_YFLIP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_B_TLBR_YFLIP, EMPTY, EMPTY, EMPTY, EMPTY, TILE_CLIFF_RIGHT, TILE_WATER],
    [TILE_WATER, TILE_CLIFF_RIGHT_XFLIP, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_CLIFF_RIGHT, TILE_WATER],
    [TILE_WATER, TILE_CLIFFBTLBR, EMPTY, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFFBTLBR, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, TILE_CLIFF_B_TLBR_XFLIP, TILE_WATER],
    [TILE_WATER, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_FOREST, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_FOREST, TILE_CLIFF_B_TLBR_XYFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_B_TLBR_YFLIP, TILE_WATER],
    [TILE_WATER, TILE_CLIFF_RIGHT_XFLIP, TILE_FOREST, TILE_GRASS, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_GRASS, EMPTY, EMPTY, TILE_FOREST, TILE_CLIFF_RIGHT, TILE_WATER],
    [TILE_WATER, TILE_CLIFF_RIGHT_XFLIP, TILE_GRASS, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, TILE_CLIFF_RIGHT, TILE_WATER],
    [TILE_WATER, TILE_CLIFFBTLBR, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TILE_GRASS, EMPTY, TILE_CLIFF_B_TLBR_XFLIP, TILE_WATER],
    [TILE_WATER, TILE_CLIFF_WATER_XFLIP, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_STAIRS, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_STRAIGHT, TILE_CLIFF_WATER, TILE_WATER]
]

def get_map(map_number: int):
    mapData = MapData
    if map_number == 1:
        return mapData.get_map1()
    elif map_number == 2:
        return mapData.get_map2()
    elif map_number == 3:
        return mapData.get_map3()
    elif map_number == 4:
        return mapData.get_map4()
    elif map_number == 5:
        return mapData.get_map5()
    elif map_number == 6: 
        return mapData.get_map6()
    elif map_number == 7:
        return mapData.get_map7()
    elif map_number == 8:
        return mapData.get_map8()
    elif map_number == 9:
        return mapData.get_map9()
    elif map_number == 10:
        return mapData.get_map10()
    else:
        return None

def cat_sprite_sheet(): return (bytearray([0, 207, 15, 15, 192, 5, 241, 244, 6, 201, 15, 15, 192, 5, 241, 244, 7, 201, 14, 15, 192, 5, 241, 244, 1, 206, 15, 15, 192, 5, 241, 244]))
def enemy_sprite_sheet(): return (bytearray([3, 143, 2, 4, 129, 1, 228, 242, 3, 143, 2, 4, 145, 17, 196, 242, 7, 139, 2, 4, 129, 1, 228, 242]), bytearray([252, 112, 253, 251, 118, 246, 27, 13, 252, 112, 253, 251, 102, 230, 59, 13, 248, 116, 253, 251, 118, 246, 27, 13]))
def button_sprite_sheet(): return (bytearray([191, 15, 31, 31, 31, 31, 15, 191, 191, 63, 127, 127, 127, 127, 63, 191]), bytearray([0, 56, 124, 124, 124, 124, 56, 0, 0, 32, 112, 112, 112, 112, 32, 0]))
def cat_head_sprite_sheet(): return (bytearray([3, 253, 254, 254, 254, 254, 253, 195, 191, 127, 255, 255, 255, 255, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 255, 255, 255, 255, 127, 191, 131, 253, 254, 254, 254, 254, 253, 3, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 126, 126, 126, 126, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 126, 126, 126, 126, 254, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 255, 255, 255, 255, 255, 227, 221, 190, 127, 127, 127, 127, 190, 221, 227, 255, 255, 255, 255, 255, 255, 227, 221, 190, 127, 127, 127, 127, 190, 221, 227, 255, 255, 255, 255, 255, 255, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 127, 127, 127, 127, 127, 127, 31, 227, 253, 254, 254, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 254, 254, 254, 253, 227, 31, 127, 127, 127, 127, 127, 127, 0]), bytearray([252, 254, 255, 255, 255, 255, 254, 252, 192, 128, 0, 0, 0, 0, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0, 0, 0, 0, 128, 192, 252, 254, 255, 255, 255, 255, 254, 252, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 227, 193, 128, 128, 128, 128, 193, 227, 255, 255, 255, 255, 255, 255, 255, 255, 227, 193, 128, 128, 128, 128, 193, 227, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 31, 3, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 3, 31, 255, 255, 255, 255, 255, 255, 255, 255]))
def selector_sprite_sheet(): return (bytearray([120, 254, 254, 255, 255, 255, 255, 254, 254, 120, 0, 1, 1, 3, 3, 3, 3, 1, 1, 0, 120, 254, 254, 255, 255, 255, 255, 254, 254, 120, 0, 1, 1, 3, 3, 3, 3, 1, 1, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]), bytearray([120, 254, 254, 255, 255, 255, 255, 254, 254, 120, 0, 1, 1, 3, 3, 3, 3, 1, 1, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 120, 254, 254, 255, 255, 255, 255, 254, 254, 120, 0, 1, 1, 3, 3, 3, 3, 1, 1, 0]))